### ISSUE TITLE
Got error when detecting the player status using other scripts

### ISSUE THREAD

**Issue by Rapiz1** [dbusjs/mpris-service#44]
I'm using a script called [player-mpris-tail](https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/player-mpris-tail/player-mpris-tail.py) for the polybar to show player status. 
It works fine with players with mpris support. It also works with mpris-service module if it's standalone. However, I got error from the script when test mpris-service with electron.

[Here's a minimal reproduce example](https://github.com/Rapiz1/mpristest)

These steps may reproduce the problem (there's a probability):
1. Run `python layer-mpris-tail.py` in the terminal
2. Open another terminal. Run `yarn && yarn start`

It may take several times to reproduce it.

And you will got the following error in the first terminal:
```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "player-mpris-tail.py", line 48, in onOwnerChangedName
    self.addPlayer(bus_name, new_owner)
  File "player-mpris-tail.py", line 66, in addPlayer
    player = Player(self._session_bus, bus_name, owner = owner, connect = self._connect, _print = self.print)
  File "player-mpris-tail.py", line 162, in __init__
    self.connect()
  File "player-mpris-tail.py", line 181, in connect
    introspect_xml = self._introspect(self.bus_name, '/')
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method 'Introspect' on interface 'org.freedesktop.DBus.Introspectable' does not exist
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "player-mpris-tail.py", line 50, in onOwnerChangedName
    self.removePlayer(old_owner)
  File "player-mpris-tail.py", line 70, in removePlayer
    self.players[owner].disconnect()
KeyError: dbus.String(':1.158')
```

I have been disturbed by the problem for long.
I create a plain nodejs script using mpris-service and a project using electron and mpris-service ( as provide above ) .
Then I  used `dbus-monitor` and compared  their output.( Their output are also contained in the above project ).It seemed that the one with electron missed something.

**Comment by acrisci** [comment]
This sort of looks like a bug in their script.

In the first error, introspecting the root node works fine for the example. You can test that with this:

> dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.nodejs / org.freedesktop.DBus.Introspectable.Introspect

And in the second, all the name owner stuff is managed by the daemon.

I'd have to go through what they are doing in more detail to learn more.

**Comment by Rapiz1** [comment]
But if you write a simple script using mpris-service and do something like `node index.js`.Then everything works fine. 
And another information that may be useful is that if you start the script after mpris-service starts, no error will be shown.
