### ISSUE TITLE
use latest dbus-next

### ISSUE THREAD

**Issue by fcastilloec** [dbusjs/mpris-service#47]
This module is using an outdated version of `dbus-next` which contains some vulnerabilities as shown by running `npm audit`. The vulnerabilities have been fixed on newer versions of `dbus-next`. Hopefully, a simple version bump is needed and there aren't any breaking changes between releases that could delay this.

**Comment by acrisci** [comment]
Yeah we can do that. Let me get publish access from @emersion .

**Comment by acrisci** [comment]
Try #48 and it works for you, I'll merge and release after I get collaborator.

**Comment by fcastilloec** [comment]
It's working fine for me and the vulnerabilities are gone. It seems the PR is having some trouble with tests especially with node v6, will it had to do with the use of `BigInt`?
Also, maybe moving the test to Github Actions might be a good idea

**Comment by acrisci** [comment]
It kind of looks like a problem with the build VM. I think I'll need to dockerize the tests to fix this issue.
